name: Build Docker image, push to docker hub and deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push identity migration image
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: APIProject/Dockerfile
          push: true
          tags: hmtken/api-project:latest

  deploy:
    name: Deploying to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd api-project-container
            # Download the latest docker-compose.yml correctly
            curl -H "Accept: application/vnd.github.v3.raw" \
                 -o docker-compose.yml \
                 https://raw.githubusercontent.com/hoangtien1105/APIProject/main/docker-compose.yml

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/api-project:latest
            docker compose down --remove-orphans
            docker compose up -d --force-recreate
            docker logs apiproject
